name: AntiPotion
version: 1.0
author: Ninjoh
main: me.Ninjoh.AntiPotion.Main
permissions:
  antipotion.*:
    children:
      antipotion.bypass:
        description: Gives permission to bypass Anti Potion.
        default: op